
name: deploy to server
'on':
  push:
    branches:
      - main
jobs:
  first_job:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        message: ["Hola", "Mundo", "CodigoFacilito"]
    steps:
      - name: Print message
        run: echo "${{ matrix.message }}"